"""initial

Revision ID: bd7d8cd6e3e0
Revises: 
Create Date: 2025-06-16 21:56:23.597633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7d8cd6e3e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timezones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('timezone_str', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timezones_store_id'), 'timezones', ['store_id'], unique=True)
    op.create_index('timezone_index', 'timezones', ['store_id'], unique=False)
    op.create_table('menu_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('dayOfWeek', sa.Integer(), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=True),
    sa.Column('end_time_local', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['timezones.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('menu_hours_index', 'menu_hours', ['store_id', 'dayOfWeek'], unique=False)
    op.create_table('store_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['timezones.store_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('store_status_index', 'store_status', ['store_id', 'timestamp_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('store_status_index', table_name='store_status')
    op.drop_table('store_status')
    op.drop_index('menu_hours_index', table_name='menu_hours')
    op.drop_table('menu_hours')
    op.drop_index('timezone_index', table_name='timezones')
    op.drop_index(op.f('ix_timezones_store_id'), table_name='timezones')
    op.drop_table('timezones')
    # ### end Alembic commands ###
