"""add store_status table

Revision ID: ce6caa1e8ac8
Revises: b9985fccf20e
Create Date: 2025-06-18 01:09:19.556073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6caa1e8ac8'
down_revision: Union[str, None] = 'b9985fccf20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_hours_store_id_fkey', 'menu_hours', type_='foreignkey')
    op.drop_constraint('store_status_store_id_fkey', 'store_status', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('store_status_store_id_fkey', 'store_status', 'timezones', ['store_id'], ['store_id'])
    op.create_foreign_key('menu_hours_store_id_fkey', 'menu_hours', 'timezones', ['store_id'], ['store_id'])
    # ### end Alembic commands ###
